### ISSUE TITLE
Another Error Importing Website

### ISSUE THREAD

**Issue by mikea888** [openlabs/magento_integration#102]
Another error occurs when importing website as follows:

OpenERP Server Error
Client Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/controllers/main.py", line 1133, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/controllers/main.py", line 1121, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 43, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 31, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 104, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 90, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/netsvc.py", line 293, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/magento_integration/wizard/import_websites.py", line 64, in import_websites
    cursor, user, instance.id, mag_website, context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/magento_integration/magento_.py", line 207, in find_or_create
    }, context=context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/orm.py", line 4434, in create
    cr.execute('insert into "'+self._table+'" (id'+upd0+") values ("+str(id_new)+upd1+')', tuple(upd2))
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "magento_root_category_id" of relation "magento_instance_website" does not exist
LINE 1: ...ebsite" (id,"instance","code","name","magento_id","magento_r...
                                                             ^

Ok

**Comment by shalabhaggarwal** [comment]
Did you do a schema upgrade of the module after pulling the latest code?

**Comment by mikea888** [comment]
No.

**Comment by shalabhaggarwal** [comment]
@mikea888 Can you confirm if the schema upgrade worked for you?

**Comment by shalabhaggarwal** [comment]
Closing this issue. Feel free to reopen if you still have this issue.
