### ISSUE TITLE
Import Orders Error "TypeError: sequence item 1: expected string or Unicode, NoneType found"

### ISSUE THREAD

**Issue by wwhhtt** [openlabs/magento_integration#105]
The module Installed and tested connection OK, import sites and catalogs all OK, but when trying to import orders I got this error:

OpenERP Server Error

Client Traceback (most recent call last):
  File "/opt/openerp/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/openerp/openerp/addons/web/controllers/main.py", line 1134, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/openerp/openerp/addons/web/controllers/main.py", line 1122, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/openerp/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/openerp/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/opt/openerp/openerp/addons/magento_integration/magento_.py", line 572, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/opt/openerp/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/opt/openerp/openerp/addons/magento_integration/sale.py", line 351, in create_using_magento_data
    cursor, user, order_data['shipping_address'], partner, context
  File "/opt/openerp/openerp/addons/magento_integration/partner.py", line 227, in find_or_create_address_as_partner_using_magento_data
    cursor, user, address, address_data
  File "/opt/openerp/openerp/addons/magento_integration/partner.py", line 251, in match_address_with_magento_data
    [address_data['firstname'], address_data['lastname']]
TypeError: sequence item 1: expected string or Unicode, NoneType found

Is there an easy way to replace any None elements with ""?

**Comment by shalabhaggarwal** [comment]
@wwhhtt This error is strange because in magento both firstname and lastname are required fields and the values for these fields is always expected to be supplied in the address data fetched from magento.

**Comment by dstags-LO** [comment]
I've had this same issue. Stack trace below. In my case, I believe I traced it back to the shipping address not being populated in magento for an order containing virtual products only. 

2013-08-15 18:33:53,250 23661 ERROR oerpdev openerp.osv.osv: Uncaught exception
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/server/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/opt/openerp/server/openerp/addons/magento_integration/magento_.py", line 572, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/opt/openerp/server/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/opt/openerp/server/openerp/addons/magento_integration/sale.py", line 351, in create_using_magento_data
    partner_obj.find_or_create_address_as_partner_using_magento_data(
  File "/opt/openerp/server/openerp/addons/magento_integration/partner.py", line 227, in find_or_create_address_as_partner_using_magento_data
    cursor, user, address, address_data
  File "/opt/openerp/server/openerp/addons/magento_integration/partner.py", line 251, in match_address_with_magento_data
    [address_data['firstname'], address_data['lastname']]
TypeError: list indices must be integers, not str
2013-08-15 18:33:53,252 23661 ERROR oerpdev openerp.netsvc: list indices must be integers, not str
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/server/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/opt/openerp/server/openerp/addons/magento_integration/magento_.py", line 572, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/opt/openerp/server/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/opt/openerp/server/openerp/addons/magento_integration/sale.py", line 351, in create_using_magento_data
    partner_obj.find_or_create_address_as_partner_using_magento_data(
  File "/opt/openerp/server/openerp/addons/magento_integration/partner.py", line 227, in find_or_create_address_as_partner_using_magento_data
    cursor, user, address, address_data
  File "/opt/openerp/server/openerp/addons/magento_integration/partner.py", line 251, in match_address_with_magento_data
    [address_data['firstname'], address_data['lastname']]
TypeError: list indices must be integers, not str

**Comment by wwhhtt** [comment]
@shalabhaggarwal Yeah I thought the same, but since I do accept express checkout using PayPal, there are some customers doesn't have any name put into Magento, all those info are from PayPal, maybe that's the issue?

How can I modify the code so that these kind of order will be import to openerp as a generic customer? Eg: first name: paypal, lastname: guest instead of NONE.

**Comment by shalabhaggarwal** [comment]
@wwhhtt I understand the case. Can you push a patch for this?

You might just have to replace address_data['firstname'] by address_data.get('firstname', '') and same for lastname.

This should do the trick.

**Comment by wwhhtt** [comment]
@shalabhaggarwal I don't know Magento/OpenERP/Python well enough to work on patches, I am sorry...

And nope...It didn't work...Change the code to address_data.get('firstname', '') and address_data.get('lastname', '') at line 251 didn't make any difference :( 

Is the error triggered by the line 251 of partner.py only? Anywhere else I should be looking at?

**Comment by kenzo55** [comment]
wwhhtt

I am getting the same error, did you resolve in the end? What should I be looking for? Does sequence item 0 mean that it is the first record or how do I identify record?

Seems to be a long period for a bug to be open

OpenERP Server Error
Client Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/magento_integration/magento_.py", line 572, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/magento_integration/sale.py", line 341, in create_using_magento_data
    context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130901_231054-py2.7.egg/openerp/addons/magento_integration/partner.py", line 168, in create_using_magento_data
    [customer_data['firstname'], customer_data['lastname']]
TypeError: sequence item 0: expected string or Unicode, NoneType found

**Comment by shalabhaggarwal** [comment]
This would happen in a case where the customer being imported from magento misses the firstname, lastname or email. I understand that these are required fields on magento and this error should not be there in first place.

This seems more like a magento side bug rather than a bug in connector.

**Comment by ghost** [comment]
Does anyone know how to get to the order-record which causes the error? I cannot find any orders with empty name fields via MySQL.

**Comment by shalabhaggarwal** [comment]
I would look into this and see if this can be handled with a preventive approach.

**Comment by ghost** [comment]
The error in my specific case was an edited, guest created order, and for some reason it didn't have the fields correct. I just deleted orders to make it work.

**Comment by l-arnold** [comment]
I have had the same problem importing Orders.  None Get imported and this (first name/last name) commonly, was the traceback.  I will check again for most recent one.  Issue may have moved by now.

We do accept PayPal and also Amazon orders through Magento, but I am not aware of issues with Address fields there.  All seem populated.

**Comment by Galaxonic** [comment]
I have a similar error wherein I am trying to import a gift card product which by default has no shipping address when sent by email. Could I solve this import error somehow?
Logically it is the correct thing not to have a shipping address unless the gift card needs to be sent by post rather than email.

**Comment by omidkosari** [comment]
Magento side checked and every first_name , last_name , emails are not empty

```
OpenERP Server Error

Client Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, **self.params)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)


Server Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/pymodules/python2.7/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/pymodules/python2.7/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/magento_.py", line 607, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/sale.py", line 351, in create_using_magento_data
    cursor, user, order_data['shipping_address'], partner, context
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/partner.py", line 227, in find_or_create_address_as_partner_using_magento_data
    cursor, user, address, address_data
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/partner.py", line 251, in match_address_with_magento_data
    [address_data['firstname'], address_data['lastname']]
TypeError: list indices must be integers, not str

```

**Comment by shalabhaggarwal** [comment]
It looks like `address_data` in line 251 is coming as a list. It is supposed to be a dictionary.

@omidkosari Would it be possible for you to provide the data dictionary as being sent by magento? We will be able to investigate the issue after we have a sample only.

**Comment by omidkosari** [comment]
Please describe what should i do to get useful info and send to you .

**Comment by omidkosari** [comment]
Here is the data that creates the problem . In magento db table with the name "sales_flat_order_address" we have following entries.

```

INSERT INTO `sales_flat_order_address` (`entity_id`, `parent_id`, `customer_address_id`, `quote_address_id`, `region_id`, `customer_id`, `fax`, `region`, `postcode`, `lastname`, `street`, `city`, `email`, `telephone`, `country_id`, `firstname`, `address_type`, `prefix`, `middlename`, `suffix`, `company`, `vat_id`, `vat_is_valid`, `vat_request_id`, `vat_request_date`, `vat_request_success`) VALUES (43, 22, 1, NULL, NULL, 1, '213123', NULL, '213123123', 'ئشسی', 'slkd\naslkdj', 'asda', 'testmail@gmail.com', '213123', 'IT', 'ئشایه', 'billing', NULL, NULL, NULL, 'سمنشتی', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sales_flat_order_address` (`entity_id`, `parent_id`, `customer_address_id`, `quote_address_id`, `region_id`, `customer_id`, `fax`, `region`, `postcode`, `lastname`, `street`, `city`, `email`, `telephone`, `country_id`, `firstname`, `address_type`, `prefix`, `middlename`, `suffix`, `company`, `vat_id`, `vat_is_valid`, `vat_request_id`, `vat_request_date`, `vat_request_success`) VALUES (44, 22, 1, NULL, NULL, 1, '213123', NULL, '213123123', 'ئشسی', 'slkd\naslkdj', 'asda', 'testmail@gmail.com', '213123', 'IT', 'ئشایه', 'shipping', NULL, NULL, NULL, 'سمنشتی', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sales_flat_order_address` (`entity_id`, `parent_id`, `customer_address_id`, `quote_address_id`, `region_id`, `customer_id`, `fax`, `region`, `postcode`, `lastname`, `street`, `city`, `email`, `telephone`, `country_id`, `firstname`, `address_type`, `prefix`, `middlename`, `suffix`, `company`, `vat_id`, `vat_is_valid`, `vat_request_id`, `vat_request_date`, `vat_request_success`) VALUES (45, 23, 1, NULL, NULL, 1, '213123', NULL, '213123123', 'ئشسی', 'slkd\naslkdj', 'asda', 'testmail@gmail.com', '213123', 'IT', 'ئشایه', 'billing', NULL, NULL, NULL, 'سمنشتی', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sales_flat_order_address` (`entity_id`, `parent_id`, `customer_address_id`, `quote_address_id`, `region_id`, `customer_id`, `fax`, `region`, `postcode`, `lastname`, `street`, `city`, `email`, `telephone`, `country_id`, `firstname`, `address_type`, `prefix`, `middlename`, `suffix`, `company`, `vat_id`, `vat_is_valid`, `vat_request_id`, `vat_request_date`, `vat_request_success`) VALUES (46, 23, 1, NULL, NULL, 1, '213123', NULL, '213123123', 'ئشسی', 'slkd\naslkdj', 'asda', 'testmail@gmail.com', '213123', 'IT', 'ئشایه', 'shipping', NULL, NULL, NULL, 'سمنشتی', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sales_flat_order_address` (`entity_id`, `parent_id`, `customer_address_id`, `quote_address_id`, `region_id`, `customer_id`, `fax`, `region`, `postcode`, `lastname`, `street`, `city`, `email`, `telephone`, `country_id`, `firstname`, `address_type`, `prefix`, `middlename`, `suffix`, `company`, `vat_id`, `vat_is_valid`, `vat_request_id`, `vat_request_date`, `vat_request_success`) VALUES (47, 24, 1, NULL, NULL, 1, '213123', NULL, '213123123', 'ئشسی', 'slkd\naslkdj', 'asda', 'testmail@gmail.com', '213123', 'IT', 'ئشایه', 'billing', NULL, NULL, NULL, 'سمنشتی', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sales_flat_order_address` (`entity_id`, `parent_id`, `customer_address_id`, `quote_address_id`, `region_id`, `customer_id`, `fax`, `region`, `postcode`, `lastname`, `street`, `city`, `email`, `telephone`, `country_id`, `firstname`, `address_type`, `prefix`, `middlename`, `suffix`, `company`, `vat_id`, `vat_is_valid`, `vat_request_id`, `vat_request_date`, `vat_request_success`) VALUES (48, 24, 1, NULL, NULL, 1, '213123', NULL, '213123123', 'ئشسی', 'slkd\naslkdj', 'asda', 'testmail@gmail.com', '213123', 'IT', 'ئشایه', 'shipping', NULL, NULL, NULL, 'سمنشتی', NULL, NULL, NULL, NULL, NULL);
```

Everything works fine until following line creates the error .As you see this line does not have shipping address . Maybe catching the exception solves the problem  `INSERT INTO `sales_flat_order_address` (`entity_id`, `parent_id`, `customer_address_id`, `quote_address_id`, `region_id`, `customer_id`, `fax`, `region`, `postcode`, `lastname`, `street`, `city`, `email`, `telephone`, `country_id`, `firstname`, `address_type`, `prefix`, `middlename`, `suffix`, `company`, `vat_id`, `vat_is_valid`, `vat_request_id`, `vat_request_date`, `vat_request_success`) VALUES (49, 25, 1, NULL, NULL, 1, '213123', NULL, '213123123', 'ئشسی', 'slkd\naslkdj', 'asda', 'testmail@gmail.com', '213123', 'IT', 'ئشایه', 'billing', NULL, NULL, NULL, 'سمنشتی', NULL, NULL, NULL, NULL, NULL);`

**Comment by Galaxonic** [comment]
Any updates on this?

**Comment by shalabhaggarwal** [comment]
@omidkosari The data which comes over to OpenERP from Magento using API would help much.

That would require putting up print statements in between python code to get the relevant data.

**Comment by shalabhaggarwal** [comment]
@Galaxonic I guess this might be too specific a case to handle. But if you think that having this feature would be generic enough and help the community, please create a separate issue describing the complete feature you propose or issue you are facing. (This is because your issue seems to be quite different from this thread.)

**Comment by wwhhtt** [comment]
OK, been trying to get to the bottom of this issue and here is what I have tried:

PM = Production magento 1.6.2 
DM = Develop magento 1.8.1 with production database
NM = New magento 1.8.1 install
OI= OpenERP 7.0 with this intergration
- OI will not work with PM with the issue originally reported
- OI will not work with DM either, same error
- OI will work with NM
- IMPORTANT: On all 3 tests done above, NONE has the correct inventory imported, all products have been imported with 0 quantity, don't know why.
- Databases of PM and DM are intact, there are no NULL values at customer first and last name fields
- I can provide database dump for analyzing if that helps

**Comment by Nivaa** [comment]
Even I have faced the same issue. But sorted it out by following traceback.

**Comment by wwhhtt** [comment]
@Nivaa Would you mind to be more specific? Traceback means logs here I guess? I am not a coder so if you can point me to the correct direction it will be really appreciated.

**Comment by Nivaa** [comment]
I have solved it by myself by tracing code. But this traceback is faced in some cases, so this should be fixed and thats why I have pointed out over here.

**Comment by shalabhaggarwal** [comment]
@Nivaa It would be nice if you can send a patch for this fix as a pull request.

**Comment by xcaliburinhand** [comment]
There are cases where a shipping address is not provided by Magento (such as downloadable content). Since order_data['shipping_address'] is empty when it gets sent to match_address_with_magento_data gets, the error occurs.

Making partner_shipping_address equal partner_invoice_address if the shipping address is not provided by Magento may be a solution.

**Comment by shruti2018** [comment]
any solution for this issue?

**Comment by omidkosari** [comment]
I agree with @xcaliburinhand
