### ISSUE TITLE
Test connection fails wit error

### ISSUE THREAD

**Issue by gracine** [openlabs/magento_integration#106]
Hi there,

I have installed the connector exactly as per your installation Guide which has actually worked fine. If I try to Test the Connection toward my Magento Store i receive the following error:

OpenERP Server Error
Client Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1128, in call_kw
    return self._call_kw(req, model, method, args, kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/pymodules/python2.7/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/pymodules/python2.7/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/wizard/test_connection.py", line 29, in default_get
    self.test_connection(cursor, user, context)
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/wizard/test_connection.py", line 47, in test_connection
    with magento.API(
AttributeError: 'module' object has no attribute 'API'

Do you have any Idea why this is not working?

**Comment by wwhhtt** [comment]
@gracine Have you created the web user and role inside Magento?

**Comment by gracine** [comment]
sure :-) Got it finally working after i updated openERP to the latest Version. Now I have the Problem that when I import orders from Magento the Customer appears 3 times. Any clue?

**Comment by gracine** [comment]
We have reinstalled opeERP and copied the module to the addons folder but we dont see the Magento extension in openERP

**Comment by gracine** [comment]
Ok. Module appears after a reboot of the System but I still have the Problem that when I import orders from Magento the Customer appears 3 times. One time as a Company and two times as a Partner.

**Comment by sharoonthomas** [comment]
@gracine Could you report the last issue as a separate bug. When you report it will help us to debug if you can put in more context.

**Comment by gracine** [comment]
Sure an thank you very much for the great effort you put into this Project. You do a great job :-)
