### ISSUE TITLE
Error creating invoices

### ISSUE THREAD

**Issue by janpfischer** [openlabs/magento_integration#109]
Hello, 

i've running a new OpenERP 7 database and Magento Comm  1.7.0.0.

The integration is set up fine and working (product import, shipment info, cancel status etc)

but if i want to create an invoice openerp give me an error.  
A Database without magento modul does not throw that error.

Error message:

``` python
Client Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/http.py", line 203, in dispatch
    response["result"] = method(self, **self.params)
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 1133, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 1121, in _call_kw
    return getattr(req.session.model(model), method)(*args, **kwargs)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 43, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 31, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 104, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)


Server Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/session.py", line 90, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 293, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/openerp/server/openerp/addons/sale/wizard/sale_make_invoice_advance.py", line 170, in create_invoices
    res = sale_obj.manual_invoice(cr, uid, sale_ids, context)
  File "/opt/openerp/server/openerp/addons/sale/sale.py", line 439, in manual_invoice
    wf_service.trg_validate(uid, 'sale.order', id, 'manual_invoice', cr)
  File "/opt/openerp/server/openerp/workflow/wkf_service.py", line 119, in trg_validate
    res2 = instance.validate(cr, id, ident, signal)
  File "/opt/openerp/server/openerp/workflow/instance.py", line 43, in validate
    workitem.process(cr, witem, ident, signal, force_running, stack=stack)
  File "/opt/openerp/server/openerp/workflow/workitem.py", line 60, in process
    ok = _split_test(cr, workitem, activity['split_mode'], ident, signal, stack)
  File "/opt/openerp/server/openerp/workflow/workitem.py", line 175, in _split_test
    _join_test(cr, t[0], t[1], ident, stack)
  File "/opt/openerp/server/openerp/workflow/workitem.py", line 183, in _join_test
    create(cr,[activity], inst_id, ident, stack)
  File "/opt/openerp/server/openerp/workflow/workitem.py", line 40, in create
    process(cr, res, ident, stack=stack)
  File "/opt/openerp/server/openerp/workflow/workitem.py", line 52, in process
    result = _execute(cr, workitem, activity, ident, stack)
  File "/opt/openerp/server/openerp/workflow/workitem.py", line 127, in _execute
    id_new = wkf_expr.execute(cr, ident, workitem, activity)
  File "/opt/openerp/server/openerp/workflow/wkf_expr.py", line 67, in execute
    return _eval_expr(cr, ident, workitem, activity['action'])
  File "/opt/openerp/server/openerp/workflow/wkf_expr.py", line 57, in _eval_expr
    ret = eval(line, env, nocopy=True)
  File "/opt/openerp/server/openerp/tools/safe_eval.py", line 241, in safe_eval
    return eval(test_expr(expr, _SAFE_OPCODES, mode=mode), globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/openerp/server/openerp/osv/orm.py", line 374, in function_proxy
    return attr(self._cr, self._uid, [self._id], *args, **kwargs)
  File "/opt/openerp/server/openerp/addons/sale_stock/sale_stock.py", line 192, in action_invoice_create
    res = super(sale_order,self).action_invoice_create( cr, uid, ids, grouped=grouped, states=states, date_invoice = date_invoice, context=context)
  File "/opt/openerp/server/openerp/addons/sale/sale.py", line 540, in action_invoice_create
    res = self._make_invoice(cr, uid, order, il, context=context)
  File "/opt/openerp/server/openerp/addons/sale/sale.py", line 408, in _make_invoice
    inv_id = inv_obj.create(cr, uid, inv, context=context)
  File "/opt/openerp/server/openerp/addons/mail/mail_thread.py", line 242, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/openerp/server/openerp/osv/orm.py", line 4478, in create
    self.pool.get(object)._store_set_values(cr, user, ids, fields2, context)
  File "/opt/openerp/server/openerp/osv/orm.py", line 4627, in _store_set_values
    result = self._columns[f].get(cr, self, ids, f, SUPERUSER_ID, context=context)
  File "/opt/openerp/server/openerp/osv/fields.py", line 1131, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/openerp/server/openerp/osv/fields.py", line 1197, in _fnct_read
    value = value[field] or False
  File "/opt/openerp/server/openerp/osv/orm.py", line 383, in __getitem__
    raise KeyError(error_msg)
KeyError: "Field 'commercial_partner_id' does not exist in object 'browse_record(res.partner, 6)'"
```

Thank you!

**Comment by shalabhaggarwal** [comment]
@b1rdhous3  This does not seem to be a connector related issue.

If there is anything that links this to the connector please let us know, else we can close this issue.

Thanks!

**Comment by janpfischer** [comment]
Hey @shalabhaggarwal 

thank you for your answer!

I don't have the issue with the OpenERP installation without Magento extention. 
Both installations are the same. Only difference is the Magento extention. So i can't imageing that the problem can be something different.

Are you using a field called "commercial_partner_id"?

Or is my installation build to old? 
Build is: 7.0-20130413-232416

**Comment by shalabhaggarwal** [comment]
@b1rdhous3 We dont use any such field in our module.

The old build can be a reason but I am not sure about this.

**Comment by sharoonthomas** [comment]
@b1rdhous3 Is the issue resolved ? Can we close this bug report ?
