### ISSUE TITLE
error importing catalog

### ISSUE THREAD

**Issue by animalelement** [openlabs/magento_integration#111]
Magento 1.7, OpenERP7. 

When I try to Import Catalog I get the following error: Are there any characters or symbols in the description of products in Magento that need to be avoided? I have some basic HTML formatting in the descriptions. 

Client Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/addons/web/controllers/main.py", line 1129, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/addons/web/controllers/main.py", line 1117, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/addons/magento_integration/wizard/import_catalog.py", line 36, in import_catalog
    product_ids = self.import_products(cursor, user, website, context)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/addons/magento_integration/wizard/import_catalog.py", line 103, in import_products
    cursor, user, mag_product['product_id'], context,
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130620_231038-py2.7.egg/openerp/addons/magento_integration/product.py", line 255, in find_or_create_using_magento_id
    product_data = product_api.info(magento_id)
  File "/opt/bitnami/python/lib/python2.7/site-packages/magento-0.5dev-py2.7.egg/magento/catalog.py", line 265, in info
    'catalog_product.info', [product, store_view, attributes]
  File "/opt/bitnami/python/lib/python2.7/site-packages/magento-0.5dev-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
ExpatError: not well-formed (invalid token): line 2, column 1246

**Comment by sharoonthomas** [comment]
You will be able to find the problem from your magento server logs. The response seems to be not well formed XML (may be an error 500 page ?)
