### ISSUE TITLE
connection time out

### ISSUE THREAD

**Issue by jaybeerivera02** [openlabs/magento_integration#118]
i get an error "connection time ou"t whenever i import catalog on openerp from magento.
What should i do for this?

**Comment by sharoonthomas** [comment]
How big is your catalog ? The module at the moment tries to import everything in one go. It may be a timeout from your server side though I agree that the module could have some pagination improvements.

**Comment by pierre-pizzetta** [comment]
Hello, I got a 900SKU catalog and it seems to take forever too, any kind of pagination would be welcome, thanks!

**Comment by JoeVoxster** [comment]
I imported 3400 SKU. Just go to sleep before starting the process. It takes hours.

**Comment by sharoonthomas** [comment]
Any good ideas for pagination ? The magento API does not seem to support pagination.

The orders are imported in a paginated way since having date boundaries works like pagination.

**Comment by JakeStoeffler** [comment]
Any updates on this isssue?  I'm trying to import a catalog of nearly 7000 products.  At first I was getting a proxy timeout after 60 seconds from my Nginx server so I increased that timeout to 8 hours.  Now I'm not getting a proxy timeout, but after about 30 minutes, the browser times out with a "XMLHTTPRequest" error and I see the following errors in my OpenERP log:

```
2014-08-27 06:35:08,375 16689 ERROR mydb openerp.osv.osv: Uncaught exception
Traceback (most recent call last):
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/openerp/v7/addons/magento_integration/wizard/import_catalog.py", line 41, in import_catalog
    product_ids = self.import_products(cursor, user, website, context)
  File "/opt/openerp/v7/addons/magento_integration/wizard/import_catalog.py", line 108, in import_products
    products.append(
  File "/opt/openerp/v7/addons/magento_integration/product.py", line 255, in find_or_create_using_magento_id
    product_data = product_api.info(magento_id)
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/catalog.py", line 265, in info
    'catalog_product.info', [product, store_view, attributes]
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
ExpatError: not well-formed (invalid token): line 27, column 61
2014-08-27 06:35:08,377 16689 ERROR mydb openerp.netsvc: not well-formed (invalid token): line 27, column 61
Traceback (most recent call last):
  File "/opt/openerp/v7/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/v7/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/openerp/v7/addons/magento_integration/wizard/import_catalog.py", line 41, in import_catalog
    product_ids = self.import_products(cursor, user, website, context)
  File "/opt/openerp/v7/addons/magento_integration/wizard/import_catalog.py", line 108, in import_products
    products.append(
  File "/opt/openerp/v7/addons/magento_integration/product.py", line 255, in find_or_create_using_magento_id
    product_data = product_api.info(magento_id)
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/catalog.py", line 265, in info
    'catalog_product.info', [product, store_view, attributes]
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py"
```

I think something is timing out, but I'm not sure what or how to change it.  Any help would be appreciated.
