### ISSUE TITLE
Error importing site

### ISSUE THREAD

**Issue by advertwine** [openlabs/magento_integration#121]
Hello,

At this moment i'm getting the following output when i'm importing a site:

Client Traceback (most recent call last):
  File "/opt/openerp/v7/web/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/openerp/v7/web/addons/web/controllers/main.py", line 1125, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/openerp/v7/web/addons/web/controllers/main.py", line 1113, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/openerp/v7/web/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/v7/web/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/v7/web/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/openerp/v7/web/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/v7/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/v7/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/v7/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/v7/addons/magento/wizard/import_websites.py", line 49, in import_websites
  File "/opt/openerp/v7/addons/magento/api.py", line 75, in get_states
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 3: 'Invalid api path.'>

I've followed all the steps at http://openerp-magento-connector.readthedocs.org/en/develop/

So i hope that you have a solution for this problem.

Kind regards,

Tom

**Comment by sharoonthomas** [comment]
The stack trace indicates justa  Fault and this means that the request to your magento site failed with an error. You are more likely to find a reason on the magento server logs.
