### ISSUE TITLE
Module doesn't show in openERP 7 on Win XP

### ISSUE THREAD

**Issue by capitaine** [openlabs/magento_integration#122]
I have Magento 1.7.0.2 installed on a linux debian server and working fine, latest openERP 7.0 from nighty build all-in-one installed on a Pc under win xp and working fine. 

I followed the step-by-step instructions at https://openerp-magento-connector.readthedocs.org/en/develop/introduction.html#installation 

I had some problems running the "python setup.py install" command (step 2.5 of the installation guide above) because it requested setuptools module for python. After installing setuptools I was able to run "python setup.py install" and I can now see the magento_.pyc and **init**.pyc compiled files.

but still can't see magento_integration module in OpenERP. When I update the modules list I get an OpenERP Server Error in a popup window which ends with "No module named magento". Same errors in openerp-server.log
I see other people have similar problem but with no solution. Somewhere I saw that one should rename the magento_integration_develop folder to magento_integration ; that didn't made any difference to my problem.
I really do not know in which direction to look. Without overcoming this obstacle I could not evaluate connectivity/synchronisation between Magento / OpenERP
Thanks for any help

Server Traceback (most recent call last):
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server\openerp\addons\web\session.py", line 89, in send
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server.\openerp\netsvc.py", line 292, in dispatch_rpc
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server.\openerp\service\web_services.py", line 626, in dispatch
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server.\openerp\osv\osv.py", line 188, in execute_kw
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server.\openerp\osv\osv.py", line 131, in wrapper
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server.\openerp\osv\osv.py", line 197, in execute
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server.\openerp\osv\osv.py", line 185, in execute_cr
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server\openerp\addons\base\module\wizard\base_module_update.py", line 42, in update_module
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server\openerp\addons\base\module\module.py", line 617, in update_list
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server\openerp\addons\web\http.py", line 580, in load_addons
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server\openerp\addons\magento_integration__init__.py", line 9, in <module>
  File "C:\Program Files\OpenERP 7.0-20130912-231158\Server\server\openerp\addons\magento_integration\magento_.py", line 17, in <module>
ImportError: No module named magento

**Comment by capitaine** [comment]
I close this ticket. I finally managed to install magento_integration after spending some dozens of hours in any kind of forums, from python to openerp, reading and reading again similar issues here, decrypting answers (!) and so on). The problem was not with the code but with the documentation who is lacking some steps (for me the solution was to copy python modules back to Server/server). I'm now crossing my fingers and my toes for next steps (importing 4K products is gooing on...)

**Comment by sharoonthomas** [comment]
We haven't tested installation on windows as none of us use it and none of our customers use it in production. The reasons we don't are similar. In linux this should have been an easy installation with just running `python setup.py install`.

However, you could fork the repository (as it has documentation too) and improve the documentation on how to install on windows.

**Comment by capitaine** [comment]
Open ERP works nice on Windows. It just doesn't care about python directory because it runs python on a dll. So you have to move the python related modules to openerp/Servers/server directory.
The installation guide is quite clear, it misses just 2-3 lines/steps. I'm not so familiar with github and forking. I'll give it a try and if I can not do it, I'll leave my instructions for these missing steps here.

**Comment by jmsalomr** [comment]
Hi,

I have the same problem in Ubuntu 12.04. I've have just open a new issue. What should I do?

Thanks in advance.

**Comment by jmsalomr** [comment]
Hi, this got solve in my issue. Just install python-setuptools using:

sudo apt-get install python-setuptools

and this get solved.

**Comment by elpeyotl** [comment]
@capitaine I have exactly the same problem! Can you please tell which files have to move to which location that it is workin in Windows? 

Got the exact same error as you posted in your first post. Thank you very much!

**Comment by capitaine** [comment]
You have to install "pycountry" and "magento"(_) modules first (and prior to this, install python-setuptools if not already there) : by default the two modules will be located at Your-Python\Lib\site-packages. 
\_ If I understood correctly developer's instructions and also my next linux experience, "magento" is installed automatically by "magento_integration", but for some reason it doesn't worked like this in my Windows install, so I had to install it separately by myself.

Then move:
1. folder of "pycountry" module from Your-Python\Lib\site-packages to Your-OpenERP\Servers\server
2. idem for "magento" folder
And now:
3. install "magento_integration" directly under Your-OpenERP\Servers\server\openerp\addons

That's all

See also my updated documentation here (not yet merged into the official/openlab's one):
https://github.com/capitaine/magento_integration/blob/patch-1/doc/source/introduction.rst

Good luck!

**Comment by premjawariya** [comment]
Just give 777 permission on the module folder problem will be solved.
