### ISSUE TITLE
export_shipment_status

### ISSUE THREAD

**Issue by capitaine** [openlabs/magento_integration#123]
Issue #97 is marked close but I still have this in the logs:

2013-09-20 07:35:57,780 1048 ERROR TLL openerp.addons.base.ir.ir_cron: Call of self.pool.get('magento.store.store_view').export_shipment_status(cr, uid, *()) failed in Job 10
Traceback (most recent call last):
  File "C:\Program Files\OpenERP 7.0-20130917-231058\Server\server\openerp\addons\base\ir\ir_cron.py", line 136, in _callback
  File "C:\Program Files\OpenERP 7.0-20130917-231058\Server\server\openerp\addons\magento_integration\magento_.py", line 626, in export_shipment_status
TypeError: 'NoneType' object does not support item assignment

I verified that I had the latest version of magento_integration and the patched lines of #97 are in the right place.

**Comment by shalabhaggarwal** [comment]
@capitaine Can you please check if all the store views have an instance associated with them?

**Comment by capitaine** [comment]
Yes, all views have an instance, the same and unique one that was created at first steps (Windows install)

I didn't have any problem with the Linux install excepted this warning in the logs : openerp.osv.osv: The method import_carriers of the object magento.instance.import_carriers can not return `None` !

In both Windows and Linux it imports "googlecheckout" among the carriers ! From what I know googlecheckout is not a carrier :)
