### ISSUE TITLE
Fault: <Fault 3: 'Invalid api path.'>

### ISSUE THREAD

**Issue by jmsalomr** [openlabs/magento_integration#129]
Hi,

I receive the following OpenERP error when I try to Import Websites:
# 

OpenERP Server Error
Client Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/pymodules/python2.7/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/pymodules/python2.7/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 49, in import_websites
    cursor, user, order_config_api.get_states(), context
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration-develop/api.py", line 75, in get_states
    return self.call('sales_order.get_order_states', [])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
# Fault: <Fault 3: 'Invalid api path.'>

I've been looking for similar posts, but all I can see is done:
- Magento installation of the Openlabs_OpenERPConnector with no errors.
- Magento cache flushed.
- The Test Connection to Magento is succesful.
- The API user has all the access rights granted.
- I have restart OpenERP service.
- I have .htpasswd allowed granting access to lacalhost, but I've tested disallowing it and doesn't work, in fact, the Test Connection works.
- My Magento URL is http://pre.domain.com . I'm using two websites for two languages. They are http://pre.domain.com/es and http://pre.domain.com/ca. I don't know if the problem could came because this. But I tried both and doesn't work neither. If i do this, the Test Connection fails.

Any idea??

**Comment by shalabhaggarwal** [comment]
@jmsalomr Please make sure the version, (i.e., 1.4.1) of magento side package is same as the one shown in this screenshot https://openerp-magento-connector.readthedocs.org/en/develop/_images/confirm-key.png

**Comment by jmsalomr** [comment]
Hi shalabhaggarwal,

Yes, this is the version. I've tried to reinstall anyway and this is the result of the Magento Connect Manager console:

Checking dependencies of packages
Installing package community/Openlabs_OpenERPConnector 1.4.1
Package community/Openlabs_OpenERPConnector 1.4.1 installed successfully
Package installed: 
 community Openlabs_OpenERPConnector 1.4.1

Cleaning cache
..
Cache cleaned successfully

I've tried again and the error persists :(

**Comment by jmsalomr** [comment]
Hi, any idea to debug the problem?

**Comment by jmsalomr** [comment]
Hi, there is nobody with the same problem?

**Comment by shalabhaggarwal** [comment]
@jmsalomr Please check the PHP/Apache logs for magento errors. The issue seems to originate from magento.

**Comment by jmsalomr** [comment]
Hi shalabhaggarwal,

I've checked apache error and access logs. Error logs are ok, access logs says the following:

Test connection:
<hostname> - - [01/Oct/2013:22:13:49 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 385 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
<hostname> - - [01/Oct/2013:22:13:50 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 355 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"

Import websites:
<hostname> - - [01/Oct/2013:22:13:08 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 384 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
<hostname> - - [01/Oct/2013:22:13:08 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 412 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
<hostname> - - [01/Oct/2013:22:13:09 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 355 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"

Magento system.log and exception.log says nothing. Do you know if there is another log to look into?

**Comment by shalabhaggarwal** [comment]
@jmsalomr I am not sure about what can be the reason behind this from the information available here.

I would advice going with professional support from a company for this solution.

**Comment by diazwatson** [comment]
Same Issue here
