### ISSUE TITLE
No Module Named Magento

### ISSUE THREAD

**Issue by l-arnold** [openlabs/magento_integration#147]
I have had a series of errors with installation.   It seems that there are dependencies that have not all installed.  The Magento Module seems to need to be installed separately (which I have done to addons/magento/  but still getting the error below when I run 

python setup.py install
from within addons/magento_integration

Any and all guidance would be appreciated.  Thank you.

This is my traceback

Server Traceback (most recent call last):
  File "/opt/openerp/web/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/server/openerp/addons/base/module/wizard/base_module_update.py", line 42, in update_module
    update, add = module_obj.update_list(cr, uid,)
  File "/opt/openerp/server/openerp/addons/base/module/module.py", line 617, in update_list
    handler.load_addons()
  File "/opt/openerp/web/addons/web/http.py", line 580, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/opt/openerp/server/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/openerp/addons/magento_integration/**init**.py", line 9, in <module>
    import magento_
  File "/opt/openerp/addons/magento_integration/magento_.py", line 17, in <module>
    import magento
  File "/opt/openerp/server/openerp/modules/module.py", line 132, in load_module
    f, path, descr = imp.find_module(module_part, ad_paths)
ImportError: No module named magento

**Comment by l-arnold** [comment]
Actually, this is the Traceback when I go to "Update Modules List" from within OpenERP.

In setup.py my last error has do do with "itsbroken", though previously it was first wanting "pycountry" then magento" which I was able to pull in each manually, but still he magento module seems to not be registering.

Wanting to perhaps "clean" and run again.  Do any Database Entries need to be cleared in Postgres?  Other guidance?

**Comment by l-arnold** [comment]
I am thinking I need to -su into my OpenERP user rather than bringing in the modules under Root.  I recall when setting up OpenERP I was quite locking into the OpenERP user and even when "chown" has been applied, I should not be running setup.py from Root.  Should do so from -su

Issue #103 here seems related to my issues.

**Comment by l-arnold** [comment]
Strangely,  if I su - (myopenerpuser) then run
pip install magento
The magento package seems to install.

however, I need to reenter Root, to run (in addons/magento_integration)
python setup.py install
but I still get the error about "itsbroken"
 .. ending w/ "error: Could not find suitable distribution for Requirement.parse('itsbroken')

Update Modules list still failing with the same Traceback.

 File "/opt/openerp/server/openerp/addons/base/module/module.py", line 617, in update_list
    handler.load_addons()
  File "/opt/openerp/web/addons/web/http.py", line 580, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/opt/openerp/server/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/openerp/addons/magento_integration/**init**.py", line 9, in <module>
    import magento_
  File "/opt/openerp/addons/magento_integration/magento_.py", line 17, in <module>
    import magento
  File "/opt/openerp/server/openerp/modules/module.py", line 132, in load_module
    f, path, descr = imp.find_module(module_part, ad_paths)
ImportError: No module named magento

**Comment by l-arnold** [comment]
I definitely recomend running a Good Snapshot before trying any of this.  Unfortunately I only ran one after I tried my first python setup.py install command...

I can go back a few weeks but don't want to.  I feel I need to clean these Modules out of the Postgres database in order to have a clean start again.

**Comment by l-arnold** [comment]
I expect some of the issue stems from "where" commands are "entered from" and to.  It is likely that my "dropping" the initial Git'd files into openerp/addons/magento_integration may have caused some problem.

It seems likely that I should have brought them in on a Root Level, then moved a created file structure for /magento and magento_integration to openerp/addons.

I am presuming but as this is my first "out of system" addon w/ Openerp 7, I am just not clear on the process.

Strange.  Yesterday when I searched for "Magento" several of the "image dependency" addons are showing up in my Module set after restart of the server.  Now I see that Magento_Integration is there (twice).  Once from the Git Install and once from the Zip Install I tried (zip folder named  "magento_integration-develop).  Will try the Git next.

Last install still hung w/ "can't find" itsbroken" dependency set....

But Magento does load as a Module now.  I see in SSH that several new modules give a Warning that they don't have "access rules.. consider adding one/some".  Lets work on the connection first though.

**Comment by l-arnold** [comment]
A few Errors.  Importing orders I get the following:  (Will follow w/ a second)

  OpenERP Server Error
Client Traceback (most recent call last):
  File "/opt/openerp/web/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/openerp/web/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/openerp/web/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/openerp/web/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/web/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/web/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/openerp/web/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/opt/openerp/addons/magento_integration/magento_.py", line 576, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/opt/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/opt/openerp/addons/magento_integration/sale.py", line 341, in create_using_magento_data
    context
  File "/opt/openerp/addons/magento_integration/partner.py", line 168, in create_using_magento_data
    [customer_data['firstname'], customer_data['lastname']]
TypeError: sequence item 0: expected string or Unicode, NoneType found

**Comment by l-arnold** [comment]
Not sure the meaning, but as above, Orders not imported.  Seems somethng in the setup/sml but not clear.  
In SSH, the following seems to come up quite frequently:  

2013-10-27 19:52:35,076 1644 ERROR active openerp.sql_db: bad query: delete from portal_wizard where id IN (1, 2, 3, 4, 5)
Traceback (most recent call last):  
  File "/opt/openerp/server/openerp/sql_db.py", line 226, in execute  
    res = self._obj.execute(query, params)  
IntegrityError: null value in column "wizard_id" violates not-null constraint  
CONTEXT:  SQL statement "UPDATE ONLY "public"."portal_wizard_user" SET "wizard_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "wizard_id
""                                                                                                                                  

2013-10-27 19:52:35,078 1644 ERROR active openerp.addons.base.ir.ir_cron: Call of self.pool.get('osv_memory.autovacuum').power_on(cr
, uid, _()) failed in Job 1  
Traceback (most recent call last):  
  File "/opt/openerp/server/openerp/addons/base/ir/ir_cron.py", line 136, in _callback  
    method(cr, uid, *args)  
  File "/opt/openerp/server/openerp/addons/base/ir/osv_memory_autovacuum.py", line 31, in power_on  
    model._transient_vacuum(cr, uid, force=True)  
  File "/opt/openerp/server/openerp/osv/orm.py", line 5191, in _transient_vacuum  
    self._transient_clean_rows_older_than(cr, self._transient_max_hours \* 60 \* 60)  
  File "/opt/openerp/server/openerp/osv/orm.py", line 5155, in _transient_clean_rows_older_than  
    self.unlink(cr, SUPERUSER_ID, ids)  
  File "/opt/openerp/server/openerp/osv/orm.py", line 3976, in unlink  
    'where id IN %s', (sub_ids,))  
  File "/opt/openerp/server/openerp/sql_db.py", line 161, in wrapper  
    return f(self, *args, *_kwargs)  
  File "/opt/openerp/server/openerp/sql_db.py", line 226, in execute  
    res = self._obj.execute(query, params)  
IntegrityError: null value in column "wizard_id" violates not-null constraint  
CON

**Comment by l-arnold** [comment]
Trying to reinstall "magento"...  getting this error now re SUDS:

root@postgresql /# easy_install magento  
install_dir /usr/local/lib/python2.6/dist-packages/  
Searching for magento  
Best match: magento 0.4  
Processing magento-0.4-py2.6.egg  
magento 0.4 is already the active version in easy-install.pth                                                                       

Using /usr/local/lib/python2.6/dist-packages/magento-0.4-py2.6.egg  
Processing dependencies for magento  
Searching for suds>=0.3.9  
Reading http://pypi.python.org/simple/suds/  
Download error: timed out -- Some packages may not be found!  
Reading http://pypi.python.org/simple/suds/  
Download error: timed out -- Some packages may not be found!  
Couldn't find index page for 'suds' (maybe misspelled?)  
Scanning index of all packages (this may take a while)  
Reading http://pypi.python.org/simple/  
Download error: timed out -- Some packages may not be found!  
No local packages or download links found for suds>=0.3.9  
error: Could not find suitable distribution for Requirement.parse('suds>=0.3.9')

**Comment by shalabhaggarwal** [comment]
Try `pip install magento`.

If the installation still fails, then it seems to be a pupi issue rather than issue with our module.

**Comment by l-arnold** [comment]
I am looking at how Python and Packages have been assembled for the build.  It seems there is a User Right issue, but it could also be that several elements simply need an update.

I have tested bringing a few other Apps in (Product Gallery, Many to Many Categories, Product Links) but this seems to make a unending Catalog Import.  

Will send an update soon.

**Comment by l-arnold** [comment]
I am trying to do this on Debian and ideally I would be able to use "apt-get" commands.  By using a few variations to get, what seemed to be missing dependencies in (pycountry) it seems I was loading some conflicting packages.

Is there a way to manually load the dependencies, then "Magento" and then "Magento-Integration"? 

For sure the system is not working reliably.  (I have at this point uninstalled from my working session of OpenERP)  I did get an import of Categories and Inventory and I proceeded to run a "update catalog" or related command to bring all of my inventory to ZERO in Magento (bummer).  However, the catalog updates seem to take forever and in the end I need to kill the screen.

I have been unable to bring in any Customers or Orders.

Thoughts on the Debian piece work would be great.  I know this is a lot of work and I appreciate what you have done here.

**Comment by l-arnold** [comment]
A few install errors I was able fix manually.
used apt-get install python-suds
mandually downloaded and installed "itsbroken" with python setup.py install

But still am left with not being able to import orders.  This is Traceback on BRAND NEW DATABASE which successfully imported PRODUCTS and CATEGORIES.  Not able to Import orders
penERP
OpenERP Server Error
Client Traceback (most recent call last):
  File "/opt/openerp/web/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/openerp/web/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/openerp/web/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/openerp/web/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/web/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/web/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/openerp/web/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/opt/openerp/addons/magento_integration/magento_.py", line 576, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/opt/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/opt/openerp/addons/magento_integration/sale.py", line 341, in create_using_magento_data
    context
  File "/opt/openerp/addons/magento_integration/partner.py", line 168, in create_using_magento_data
    [customer_data['firstname'], customer_data['lastname']]
TypeError: sequence item 0: expected string or Unicode, NoneType found

REQUESTING A REOPEN

**Comment by l-arnold** [comment]
Lets close this for now.  There seems to be an issue with Magento Module being shaddowed now (after multiple installs).  Will open new issue with specifics.
