### ISSUE TITLE
<Fault 4: 'Resource path is not callable.'>

### ISSUE THREAD

**Issue by Jagdish-Panchal** [openlabs/magento_integration#148]
Hello,

I have install magento_intigration-develop module in openerp 7 it work fine, test connection also done but when i click on import website its give me below error:

Traceback (most recent call last):
  File "/home/jagdish/workspace/openerp/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/jagdish/workspace/openerp/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/jagdish/workspace/openerp/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/jagdish/workspace/openerp/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 51, in import_websites
    cursor, user, order_config_api.get_states(), context
  File "/home/jagdish/workspace/openerp/openerp/addons/magento_integration-develop/api.py", line 75, in get_states
    return self.call('sales_order.get_order_states', [])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.**send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(*_self._stack[0])
Fault: <Fault 4: 'Resource path is not callable.'>
2013-10-28 11:05:58,977 19267 ERROR openerp openerp.netsvc: 
Traceback (most recent call last):
  File "/home/jagdish/workspace/openerp/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/jagdish/workspace/openerp/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/home/jagdish/workspace/openerp/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/jagdish/workspace/openerp/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/jagdish/workspace/openerp/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/jagdish/workspace/openerp/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/jagdish/workspace/openerp/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 51, in import_websites
    cursor, user, order_config_api.get_states(), context
  File "/home/jagdish/workspace/openerp/openerp/addons/magento_integration-develop/api.py", line 75, in get_states
    return self.call('sales_order.get_order_states', [])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 4: 'Resource path is not callable.'>

**Comment by Jagdish-Panchal** [comment]
Pls .. Any solution  ?????

**Comment by shalabhaggarwal** [comment]
Which version of magento are you using?

Also the module name should be magento_integration and not magento_integration-develop

**Comment by Jagdish-Panchal** [comment]
Openerp version - 7

python 2.7

magento 1.7.0.2

python magento module : magento-develop and magento-0.4(both install)

I have try Both module magento_integration and magento_integration-develop

getting another error:( i have post issue for this error also https://github.com/openlabs/magento_integration/issues/160)

Traceback (most recent call last):
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/jagdish/workspace/balmond_openerp/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 49, in import_websites
    cursor, user, order_config_api.get_states(), context
  File "/home/jagdish/workspace/balmond_openerp/openerp/addons/magento_integration-develop/api.py", line 75, in get_states
    return self.call('sales_order.get_order_states', [])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.5dev-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.**send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
ExpatError: syntax error: line 2, column 0
2013-11-09 07:28:33,637 17534 ERROR balmond_new openerp.netsvc: syntax error: line 2, column 0
Traceback (most recent call last):
  File "/home/jagdish/workspace/balmond_openerp/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/jagdish/workspace/balmond_openerp/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/jagdish/workspace/balmond_openerp/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 49, in import_websites
    cursor, user, order_config_api.get_states(), context
  File "/home/jagdish/workspace/balmond_openerp/openerp/addons/magento_integration-develop/api.py", line 75, in get_states
    return self.call('sales_order.get_order_states', [])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.5dev-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
ExpatError: syntax error: line 2, column 0

**Comment by ttwhy** [comment]
the headline points to a simultaneous problem like this: https://github.com/openlabs/magento_integration/issues/116

**Comment by sharoonthomas** [comment]
Closing the issue as the discussion should probably continue on #116.
