### ISSUE TITLE
Scheduled order import doesn't work

### ISSUE THREAD

**Issue by ToRvaLDz** [openlabs/magento_integration#152]
Manually import orders from magento is ok, while scheduling it generate an error:

<pre><code>2013-11-01 18:15:01,248 5664 ERROR xxx openerp.addons.base.ir.ir_cron: Call of self.pool.get('magento.store.store_view').import_orders(cr, uid, *()) failed in Job 9
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_cron.py", line 136, in _callback
    method(cr, uid, *args)
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/magento_.py", line 520, in import_orders
    cursor, user, store_view, context
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/magento_.py", line 607, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/sale.py", line 367, in create_using_magento_data
    cursor, user, order_data, context
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/sale.py", line 445, in get_item_line_data_using_magento_data
    context=context
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/product.py", line 255, in find_or_create_using_magento_id
    product_data = product_api.info(magento_id)
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/catalog.py", line 265, in info
    'catalog_product.info', [product, store_view, attributes]
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: Fault 101: 'Product not exists.'</code></pre>

**Comment by shalabhaggarwal** [comment]
@ToRvaLDz This error is because a product which has been used in an order was deleted later.

It is always advised not delete a product or category once it has been used on an order.

**Comment by ToRvaLDz** [comment]
I think the problem is that the cron job is trying to import the orders of a store view that I haven't configured and it cannot find the product, I suggest to add a checkbox to enable cron jobs per store. 

Thank you

**Comment by StuckInLoop** [comment]
so there is no other way around this?
