### ISSUE TITLE
Unable to import orders.  Success w/ Products and Categories

### ISSUE THREAD

**Issue by l-arnold** [openlabs/magento_integration#154]
In Brand NEW DATABASE as DESCRIBED.  Able to import Products and Categories.  However, again, not able to import Orders  (as stated in Module Magento Issue recently closed).  This is the current traceback.  Guidance would be helpful.  Seems to indicate a "unicode" issue but I am not clear about this.

OpenERP Server Error
Client Traceback (most recent call last):
  File "/opt/openerp/web/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/openerp/web/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/openerp/web/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/openerp/web/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/web/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/web/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/openerp/web/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/opt/openerp/addons/magento_integration/magento_.py", line 576, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/opt/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/opt/openerp/addons/magento_integration/sale.py", line 341, in create_using_magento_data
    context
  File "/opt/openerp/addons/magento_integration/partner.py", line 168, in create_using_magento_data
    [customer_data['firstname'], customer_data['lastname']]
TypeError: sequence item 0: expected string or Unicode, NoneType found

**Comment by l-arnold** [comment]
In OpenERP, res.partner database
Field  "name" varchar(128) NOT NULL,

I see nothing in OpenERP related to First Name / Last name.  Likely from Magento

Should the whole file structure somehow be set up differently.  I am not clear where to do that.

looking forward
I would like the possibility of tracking "Companies" rather than individuals for recievable and account tracking.  I saw reference of this issue in related issue, also I recall this being a problem in ver 6 (magento openerp connect)

**Comment by l-arnold** [comment]
In Magento:  customer_address_entity (and sub databases) are innodb with collation:  utf8_general_ci
Including customer_address_entity_varchar and customer_address_entity_text

All fields are populated
First Name = attribute_id  19
Last Name = attribute_id 21
Company = attribute_id 23

There is a strange entry in Object Properties (Navicat) (to me) of Max Data Length = 0 Bytes (0) even though all files are full of Data.  I doubt this is related.

**Comment by l-arnold** [comment]
ongoing issue.  I believe I will be able to at least update Magento Inventory from OpenERP now.  I expect incoming orders will be problematic with inventory (as they are not importing, but I assume Magento will proceed to update inventory).

OpenERP shows inventory  at Zero and when Catalog is updated, all Magento Items become Zero.  Protocol for this should be spelled out.  Likely Manual entry from Open ERP, but should items be declared "consumable" or "stockable"?

**Comment by sharoonthomas** [comment]
[customer_data['firstname'], customer_data['lastname']] in the example refer to data coming in from magento. Probably the data from magento is invalid ?

**Comment by shalabhaggarwal** [comment]
This is same as #105 

This happens because magento does not implement its constraints at all levels.

**Comment by l-arnold** [comment]
I am closing for now in that I have gone back to previous snapshot and cannot replicate.  Thank you for your efforts.
