### ISSUE TITLE
Error when click Import website 

### ISSUE THREAD

**Issue by Jagdish-Panchal** [openlabs/magento_integration#160]
I have configure magento_intigreion-devlope module in my openerp, i have click on test connection button it give  me message connection successful, but when i click on Import website button it give me following error

Openerp version - 7
python 2.7
magento  1.7.0.2
python magento module : magento-develop

Error Message :   

2013-11-09 06:53:08,715 16458 ERROR balmond_new openerp.osv.osv: Uncaught exception
Traceback (most recent call last):
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/jagdish/workspace/balmond_openerp/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 49, in import_websites
    cursor, user, order_config_api.get_states(), context
  File "/home/jagdish/workspace/balmond_openerp/openerp/addons/magento_integration-develop/api.py", line 75, in get_states
    return self.call('sales_order.get_order_states', [])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.5dev-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.**send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
ExpatError: syntax error: line 2, column 0
2013-11-09 06:53:08,719 16458 ERROR balmond_new openerp.netsvc: syntax error: line 2, column 0
Traceback (most recent call last):
  File "/home/jagdish/workspace/balmond_openerp/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/jagdish/workspace/balmond_openerp/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/jagdish/workspace/balmond_openerp/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/jagdish/workspace/balmond_openerp/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 49, in import_websites
    cursor, user, order_config_api.get_states(), context
  File "/home/jagdish/workspace/balmond_openerp/openerp/addons/magento_integration-develop/api.py", line 75, in get_states
    return self.call('sales_order.get_order_states', [])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.5dev-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
ExpatError: syntax error: line 2, column 0

**Comment by Jagdish-Panchal** [comment]
Pls. reply

**Comment by shalabhaggarwal** [comment]
This is most probably an issue with the XML data sent by magento and not an issue with connector itself.

This should debug this at the RPC level or you can take professional help for the same.

**Comment by Jagdish-Panchal** [comment]
Hi, 

Thanks for your reply. 

Could you please provide me latest module( magento_integration) and connector, Also give step of Configuration with magento and Openerp.

**Comment by shalabhaggarwal** [comment]
All the modules and libraries on github are up to date.

Please refer the same for latest code.

**Comment by atuljain** [comment]
Hello 
Please reply here
What is the solution for above mentioned error 

File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
p.feed(data)
File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
self._parser.Parse(data, 0)
ExpatError: syntax error: line 2, column 0

if is this rpc error , 
should we need to do modify at magento or something else 
and please refer some example for this kind of error/bug
