### ISSUE TITLE
Error when Importing Orders

### ISSUE THREAD

**Issue by coruble** [openlabs/magento_integration#164]
Hello,

trying to import orders for the first time on a fresh system gives me the following error, any ideas ? thanks !

Client Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/magento_integration/magento_.py", line 607, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/usr/lib/python2.6/site-packages/openerp-7.0_20131123_002432-py2.6.egg/openerp/addons/magento_integration/sale.py", line 355, in create_using_magento_data
    'name': instance.order_prefix + order_data['increment_id'],
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

**Comment by sharoonthomas** [comment]
Not really sure, but one of the following values is a boolean:
- order_prefix
- increment_id of the order

The easy one to test would be order_prefix. Can you check your instance definition if the order_prefix is specified ?

**Comment by coruble** [comment]
Hello Sharoon, thanks for the quick answer !
Well that was easy, there was no order_prefix specified.
Works like a charm now.
Thanks a lot, and sorry for the stupid issue !

**Comment by coruble** [comment]
I have some questions for you regarding cron scheduling, unrelated to this misconfiguration issue.
Can I contact you at <removed-email> ?
Thanks !

**Comment by sharoonthomas** [comment]
Please create issues on github (unless you already have an openlabs support account).

**Comment by strauss69400** [comment]
hello,

I get the same error but i dont understand.
what should we put in this field?i search in magento and i don't found this value.

hoping you can help me.thanks
