### ISSUE TITLE
Module Magento not found  error

### ISSUE THREAD

**Issue by shrikanthnk** [openlabs/magento_integration#207]
Magento is successfully installed in WAMP Server . Also magento connecter has been added.

Later downloaded the module 'magento_integration__develop' module and placed inside addons directory. Clicking upon update module of the openerp pops up following error .

module 'Magento' no found

**Comment by dorfao** [comment]
I have the same issue, but i'm using a debian 7.4, and i install openerp using the openerp apt command in the openerp official site.

i read the  magento_integration installation doc use the exact command that was in the doc. install pyton magento api using "pip install magento", and  when i put the  folder in the openerp addons path, i get this info on my log, and openerp doesn't work.

if i disable magento_integration the openerp work fine.

the log:

2014-04-01 04:53:11,973 18880 INFO ? openerp.service: Initiating shutdown
2014-04-01 04:53:11,973 18880 INFO ? openerp.service: Hit CTRL-C again or send a second signal to force the shutdown.
2014-04-01 04:53:13,383 18923 INFO ? openerp: OpenERP version 7.0-20140330-231328
2014-04-01 04:53:13,383 18923 INFO ? openerp: addons paths: /etc/openerp/addon/loc_brasil/l10n_br_core,/etc/openerp/addon/fiscal/fiscal_rules,/etc/openerp/addon/magento/magento_integration
2014-04-01 04:53:13,384 18923 INFO ? openerp: database hostname: localhost
2014-04-01 04:53:13,384 18923 INFO ? openerp: database port: 5432
2014-04-01 04:53:13,384 18923 INFO ? openerp: database user: openerp
2014-04-01 04:53:14,061 18923 INFO ? openerp.addons.google_docs.google_docs: GData lib version `%s GData-Python/2.0.17` detected
2014-04-01 04:53:14,210 18923 CRITICAL ? openerp.modules.module: Couldn't load module web
2014-04-01 04:53:14,211 18923 CRITICAL ? openerp.modules.module: No module named magento
2014-04-01 04:53:14,211 18923 ERROR ? openerp.service: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/service/**init**.py", line 60, in load_server_wide_modules
    openerp.modules.module.load_openerp_module(m)
  File "/usr/lib/pymodules/python2.7/openerp/modules/module.py", line 415, in load_openerp_module
    getattr(sys.modules['openerp.addons.' + module_name], info['post_load'])()
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 628, in wsgi_postload
    openerp.wsgi.register_wsgi_handler(Root())
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 517, in **init**
    self.load_addons()
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 580, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/usr/lib/pymodules/python2.7/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/pymodules/python2.7/openerp/addons/mrp/**init**.py", line 22, in <module>
    import mrp
  File "/usr/lib/pymodules/python2.7/openerp/addons/mrp/mrp.py", line 33, in <module>
    from openerp.addons.product import _common
  File "/usr/lib/pymodules/python2.7/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/etc/openerp/addon/magento/magento_integration/product.py", line 8, in <module>
    import magento
  File "/usr/lib/pymodules/python2.7/openerp/modules/module.py", line 132, in load_module
    f, path, descr = imp.find_module(module_part, ad_paths)
ImportError: No module named magento
2014-04-01 04:53:14,230 18923 INFO ? openerp: OpenERP server is running, waiting for connections...

**Comment by theprovensupport** [comment]
I just downloaded the module and got the same issue as above. Can anyone please help to provide solution for this error?

Thanks...

**Comment by atuljain** [comment]
run these command

sudo apt-get install python-pip

pip install magento
change the name of module like "magento_integration"

**Comment by theprovensupport** [comment]
Hi Atul,

Thanks for your feedback. It worked for me. 

Can you please do me one more favor? Can you please let me know how can I generate Magento API keys to enter inside "Magento Instances" screen of OpenERP.

Looking forward to your revert.

Thanks...

**Comment by shrikanthnk** [comment]
Sorry  Sir..

I'm new to this and learning this technology...

If you don't mind can you share complete steps  as well as module with me
so as to integrate openerp with magento

On Wed, Apr 9, 2014 at 11:40 PM, theprovensupport
notifications@github.comwrote:

> Hi Atul,
> 
> Thanks for your feedback. It worked for me.
> 
> Can you please do me one more favor? Can you please let me know how can I
> generate Magento API keys to enter inside "Magento Instances" screen of
> OpenERP.
> 
> Looking forward to your revert.
> 
> Thanks...
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/openlabs/magento_integration/issues/207#issuecomment-39997400
> .

## 

Thanks,
Shrikanth Nayak

**Comment by pvd276** [comment]
i'm install "openerp all in one" in windows 8
where i can use command?
after i install openerp, i copy magento_integration to addons folder, but it show error "No handler found"

i lose some steps ?

**Comment by atuljain** [comment]
you need to install python magento package on your system 
you can use here pip 
 http://www.pip-installer.org/en/latest/installing.html

Download get-pip.py, being careful to save it as a .py file rather than .txt. Then, run it from the command prompt.
python get-pip.py
then install magento package 
download from here or refer this link for installation 
https://pypi.python.org/pypi/magento

**Comment by pvd276** [comment]
i'm setup pip, magento, pycountry and copy it to server\server
everything ok, i see log server, no error
but module magento_integration not show in update list and module installed

**Comment by mic4ae1** [comment]
You should put your module here /usr/lib/pymodules/python2.7/openerp/addons unlike commonly misplaced to /usr/share/pyshared/openerp/addons

change ownership: sudo chown -R root.root usr/lib/pymodules/python2.7/openerp/addons/module_name

change permissions of the module: sudo chmod 755 /usr/lib/pymodules/python2.7/openerp/addons/module_name -R

restart the server: sudo service openerp restart
