### ISSUE TITLE
Import Sale Order

### ISSUE THREAD

**Issue by atuljain** [openlabs/magento_integration#214]
While Import sales order 

Traceback (most recent call last):
  File "/home/atul/openerp-8/openerp/http.py", line 345, in dispatch
    response["result"] = self._call_function(*_self.params)
  File "/home/atul/openerp-8/openerp/http.py", line 217, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/atul/openerp-8/openerp/service/model.py", line 112, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/atul/openerp-8/openerp/http.py", line 212, in checked_call
    return self.func(_a, *_kw)
  File "/home/atul/openerp-8/openerp/http.py", line 528, in __call__
    return self.method(_args, *_kw)
  File "/home/atul/openerp-8/openerp/addons/web/controllers/main.py", line 1207, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/atul/openerp-8/openerp/addons/web/controllers/main.py", line 1195, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/atul/openerp-8/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/home/atul/openerp-8/openerp/addons/magento_integration/magento_.py", line 605, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/home/atul/openerp-8/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/home/atul/openerp-8/openerp/addons/magento_integration/sale.py", line 307, in create_using_magento_data
    if not store_view.shop:
  File "/home/atul/openerp-8/openerp/osv/orm.py", line 500, in **getattr**
    return self[name]
  File "/home/atul/openerp-8/openerp/osv/orm.py", line 408, in **getitem**
    field_values = self._table.read(self._cr, self._uid, ids, field_names, context=self._context, load="_classic_write")
  File "/home/atul/openerp-8/openerp/osv/orm.py", line 3240, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/home/atul/openerp-8/openerp/osv/orm.py", line 3356, in _read_flat
    res2 = self._columns[f].get(cr, self, ids, f, user, context=context, values=res)
  File "/home/atul/openerp-8/openerp/osv/fields.py", line 1210, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/atul/openerp-8/openerp/osv/fields.py", line 1286, in _fnct_read
    value_name = dict(obj.pool[self._obj].name_get(cr, SUPERUSER_ID, value_ids, context=context))
  File "/home/atul/openerp-8/openerp/modules/registry.py", line 103, in __getitem__
    return self.models[model_name]
AttributeError: Got KeyError('res.companySales Shop',) while trying to get attribute shop on a magento.store.store_view record.

**Comment by sharoonthomas** [comment]
We dont officially support openerp 8 yet.
