### ISSUE TITLE
404 message on IE after copy this unzipped folder to addons

### ISSUE THREAD

**Issue by masterbor** [openlabs/magento_integration#216]
Hi, 
I downloaded the latest versión of OpenERP (Windows Version) and the zip file for openlabs/magento_integration from here.
After install OpenERP it works fine. 
Then I uncompress and copy the magento_integration-develop folder into the addons folder and restart the OpenERP service. After that I see a 404 message on IE.

Log error extract:

2014-04-14 17:27:41,700 2632 CRITICAL ? openerp.modules.module: Couldn't load module web
2014-04-14 17:27:41,700 2632 CRITICAL ? openerp.modules.module: No module named magento
2014-04-14 17:27:41,700 2632 ERROR ? openerp.service: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenERP 7.0-20140214-002644\Server\server.\openerp\service__init__.py", line 60, in load_server_wide_modules
  File "C:\Program Files (x86)\OpenERP 7.0-20140214-002644\Server\server.\openerp\modules\module.py", line 415, in load_openerp_module
  File "C:\Program Files (x86)\OpenERP 7.0-20140214-002644\Server\server\openerp\addons\web\http.py", line 628, in wsgi_postload
  File "C:\Program Files (x86)\OpenERP 7.0-20140214-002644\Server\server\openerp\addons\web\http.py", line 517, in **init**
  File "C:\Program Files (x86)\OpenERP 7.0-20140214-002644\Server\server\openerp\addons\web\http.py", line 580, in load_addons
  File "C:\Program Files (x86)\OpenERP 7.0-20140214-002644\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20140214-002644\Server\server\openerp\addons\magento_integration_develop__init__.py", line 9, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20140214-002644\Server\server\openerp\addons\magento_integration_develop\magento_.py", line 17, in <module>
ImportError: No module named magento 

Can you help me?
Thanks in advance.
Regards.

**Comment by atuljain** [comment]
change the name of this folder "magento_integration" instead of "magento_integration_develop"

**Comment by masterbor** [comment]
I rename the folder to "magento_integration", same problem…

De: Atul [mailto:notifications@github.com] 
Enviado el: martes, 15 de abril de 2014 02:04 a.m.
Para: openlabs/magento_integration
CC: masterbor
Asunto: Re: [magento_integration] 404 message on IE after copy this unzipped folder to addons (#216)

change the name of this folder "magento_integration" instead of "magento_integration_develop"

**Comment by atuljain** [comment]
Sorry you have to instll magento on your system
run this command
sudo apt-get install python-pip
pip install magento

**Comment by masterbor** [comment]
Where I must run: pip install magento ?

PD: OpenERP is installed on Windows.

De: Atul [mailto:notifications@github.com] 
Enviado el: martes, 15 de abril de 2014 09:22 a.m.
Para: openlabs/magento_integration
CC: masterbor
Asunto: Re: [magento_integration] 404 message on IE after copy this unzipped folder to addons (#216)

Sorry you have to instll magento on your system
run this command
pip install magento

**Comment by atuljain** [comment]
actually i am not familar with windows but you can find it  on google
might be you have to run this commands 
python -m pip install -U pip but first download pip from python package

**Comment by atuljain** [comment]
you can find here 
https://pypi.python.org/pypi/magento
