### ISSUE TITLE
Magento OpenERP Integration error when importing websites Fault: <Fault 3: 'Invalid api path.'>

### ISSUE THREAD

**Issue by hbswell** [openlabs/magento_integration#230]
The connector is successfully installed and the connection test is working fine too but I am getting the following error message when trying to import the websites :

OpenERP Server Error
Client Traceback (most recent call last):
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/addons/web/http.py", line 204, in dispatch
response["result"] = method(self, self.params)
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/addons/web/controllers/main.py", line 1132, in call_button
action = self._call_kw(req, model, method, args, {})
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/addons/web/controllers/main.py", line 1120, in callkw
return getattr(req.session.model(model), method)(*args, kwargs)
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/addons/web/session.py", line 42, in proxy
result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/addons/web/session.py", line 30, in proxy_method
result = self.session.send(self.service_name, method, *args)
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/addons/web/session.py", line 103, in send
raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/addons/web/session.py", line 89, in send
return openerp.netsvc.dispatch_rpc(service_name, method, args)
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/netsvc.py", line 296, in dispatch_rpc
result = ExportService.getService(service_name).dispatch(method, params)
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/service/web_services.py", line 626, in dispatch
res = fn(db, uid, params)
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/osv/osv.py", line 190, in execute_kw
return self.execute(db, uid, obj, method, args, kw or {})
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/osv/osv.py", line 132, in wrapper
return f(self, dbname, _args, kwargs)
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/osv/osv.py", line 199, in execute
res = self.execute_cr(cr, uid, obj, method, args, *_kw)
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/osv/osv.py", line 187, in execute_cr
return getattr(object, method)(cr, uid, args, kw)
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/addons/magento_integration/wizard/import_websites.py", line 49, in import_websites
cursor, user, order_config_api.get_states(), context
File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140330_231328-py2.7.egg/openerp/addons/magento_integration/api.py", line 75, in get_states
return self.call('sales_order.get_order_states', [])
File "/opt/bitnami/python/lib/python2.7/site-packages/magento/api.py", line 161, in call
return self.client.call(self.session, resource_path, arguments)
File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1224, in call return self.__send(self.__name, args)
File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1578, in request
verbose=self.verbose
File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1264, in request
return self.single_request(host, handler, request_body, verbose)
File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1297, in single_request
return self.parse_response(response)
File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
return u.close()
File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 793, in close
raise Fault(self._stack[0])
Fault: <Fault 3: 'Invalid api path.'>

I manually installed the connector on the magento side (not through magenta connect) downloaded from bazaar, and followed and doubled checked these steps :

-Move the Openlabs folder in the magento_root/app/code/community.
-Move the file app/etc/modules/Openlabs_OpenERPConnector.xml in magento_root/app/etc/modules.
-Flush the Magento cache from the admin panel or by removing everything in magento_root/var/cache

The only question mark I have regarding this install is that I am running Magento 1.9 with PHP 5.4 and did not install the PHP 5.3 patch since Magento 1.9 supports PHP 5.4 but not sure if it would have any impact on the connector.

Any advice would be greatly appreciated.

**Comment by AaronKaa** [comment]
Did you get anywhere with this issue - im seeing the same
