### ISSUE TITLE
Catalog Import Error - Parse Error?

### ISSUE THREAD

**Issue by loftwerks** [openlabs/magento_integration#236]
When I try to Import Catalog I get the following error: From what I'm finding in various forums, it appears upon import, as soon as any number of characters are encountered the parse fails.  Is there a way of escaping those characters? - "&, <>, etc..."

Magento v1.9 
## Odoo v8

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 539, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 292, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 755, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 388, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/magento_integration/wizard/import_catalog.py", line 36, in import_catalog
    product_ids = self.import_products(cursor, user, website, context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/magento_integration/wizard/import_catalog.py", line 93, in import_products
    store_view=website.stores[0].store_views[0].magento_id
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/catalog.py", line 253, in list
    return self.call('catalog_product.list', [filters, store_view])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
ExpatError: not well-formed (invalid token): line 2, column 1048230

**Comment by sharoonthomas** [comment]
Not sure this is about the characters. This is probably magento raising an error and the error message is not well-formed (like a http error page). This results in the api presenting an error and stacktrace like the one you have pasted.

A good place to check would be magento logs (or web server logs).
