### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by AnushaTeleparadigm** [openlabs/magento_integration#237]
Does the module  support the versions:
Magento 1.8
OpenERP 7.0

**Comment by sharoonthomas** [comment]
It should. Are you facing issues ?

**Comment by AnushaTeleparadigm** [comment]
yes when im imporing product or orders getting Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/openerp/addons/connector/queue/worker.py", line 123, in run_job job.perform(session) File "/usr/lib/python2.7/dist-packages/openerp/addons/connector/queue/job.py", line 492, in perform self.result = self.func(session, _self.args, *_self.kwargs) File "/usr/lib/python2.7/dist-packages/openerp/addons/magentoerpconnect/unit/import_synchronizer.py", line 378, in import_record importer.run(magento_id, force=force) File "/usr/lib/python2.7/dist-packages/openerp/addons/magentoerpconnect/unit/import_synchronizer.py", line 221, in run self._import_dependencies() File "/usr/lib/python2.7/dist-packages/openerp/addons/magentoerpconnect/sale.py", line 849, in _import_dependencies 'magento.product.product') File "/usr/lib/python2.7/dist-packages/openerp/addons/magentoerpconnect/unit/import_synchronizer.py", line 124, in _import_dependency importer.run(magento_id) File "/usr/lib/python2.7/dist-packages/openerp/addons/magentoerpconnect/unit/import_synchronizer.py", line 206, in run self.magento_record = self._get_magento_data() File "/usr/lib/python2.7/dist-packages/openerp/addons/magentoerpconnect/unit/import_synchronizer.py", line 63, in _get_magento_data return self.backend_adapter.read(self.magento_id) File "/usr/lib/python2.7/dist-packages/openerp/addons/magentoerpconnect/product.py", line 278, in read [int(id), storeview_id, attributes, 'id']) File "/usr/lib/python2.7/dist-packages/openerp/addons/magentoerpconnect/product.py", line 243, in _call return super(ProductProductAdapter, self)._call(method, arguments) File "/usr/lib/python2.7/dist-packages/openerp/addons/magentoerpconnect/unit/backend_adapter.py", line 168, in _call result = api.call(method, arguments) File "/usr/local/lib/python2.7/dist-packages/magento/api.py", line 161, in call return self.client.call(self.session, resource_path, arguments) File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__ return self.__send(self.__name, args) File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request verbose=self.__verbose File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request return self.single_request(host, handler, request_body, verbose) File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request return self.parse_response(response) File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response return u.close() File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close raise Fault(**self._stack[0]) 
line 793, in close raise Fault(**self._stack[0]) Fault: <Fault 3: 'Invalid api path.'>
Fault: <Fault 3: 'Invalid api path.'> error

Magento 1.7
OpenERP7.0
ubuntu 14.04LTS

**Comment by sharoonthomas** [comment]
have you installed the magento side extension and refreshed the magento cache ?

**Comment by AnushaTeleparadigm** [comment]
yes i did and im able to import websites, customer groups and categories from magento

**Comment by sharoonthomas** [comment]
You should check the magento webserver for the reason for the crash. This seems to be an RPC error and if you are using apache that is where a clue will be there to what the problem is.

**Comment by AnushaTeleparadigm** [comment]
im sure their is no problem with my magento webserver and i verified their is no errors in my webserver log file...
Thanks

**Comment by AnushaTeleparadigm** [comment]
God! .Now im able to import everything from my magento by installing new latest magento connector from https://code.launchpad.net/~magentoerpconnect-core-editors/magentoerpconnect/module-magento-trunk
Thanks.
