### ISSUE TITLE
Fault: <Fault 3: 'Invalid api path.'>

### ISSUE THREAD

**Issue by jagdishpanchal** [openlabs/magento_integration#61]
Hello 

I have install magento-integration-develop module and did connection with magento it successfully connected but when i click on Import site button it open wizard and i click on continue button it give me error bellow

Traceback (most recent call last):
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/osv/osv.py", line 198, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/addons/magento-integration-develop/wizard/import_websites.py", line 58, in import_websites
    mag_websites = core_api.websites()
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/addons/magento-integration-develop/api.py", line 27, in websites
    return self.call('ol_websites.list', [])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.1.5dev-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.**send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(*_self._stack[0])
Fault: <Fault 3: 'Invalid api path.'>
2013-07-12 05:28:51,256 5626 ERROR openerp_7 openerp.netsvc: 
Traceback (most recent call last):
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/netsvc.py", line 295, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/service/web_services.py", line 614, in dispatch
    res = fn(db, uid, *params)
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/osv/osv.py", line 198, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/addons/magento-integration-develop/wizard/import_websites.py", line 58, in import_websites
    mag_websites = core_api.websites()
  File "/home/jagdish/workspace/openerp-7.0-school_date01_07/openerp/addons/magento-integration-develop/api.py", line 27, in websites
    return self.call('ol_websites.list', [])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.1.5dev-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 3: 'Invalid api path.'>

So please Help 

Thanks And regards
Jagdish

**Comment by sharoonthomas** [comment]
The problem seems to be with the API call for ol_websites.list. Can you confirm that you did the following:
- [ ] Installed magento side extension (http://www.magentocommerce.com/magento-connect/open-erp-connector-by-openlabs.html)
- [ ] Flushed magento cache (needed for the new api's to be available) after installing the above extension ?

Since you are able to test the connection, it looks like your API username and password are working. However, make sure that the API user's role allows access to "All" objects.

**Comment by jagdishpanchal** [comment]
Hello 

I have try both version

Opernp(magento-integration-develop version 7)   and  My magento version is 1.7

Magento Connect 1.0 when i click on install in magento admin panel  got error like
   Couldn't resolve host 'magento-community'

Magento Connect 2.0 
     I have paste this link in to http://connect20.magentocommerce.com/community/Openlabs_OpenERPConnector
     Got error like community/Openlabs_OpenERPConnector: Extension is 'beta' please check(or change) stability settings on Magento Connect Manager

Thanks
jagdish

**Comment by sharoonthomas** [comment]
You have to set the extension state to beta. See the section on "Installation of Magento extension" on [this page](http://openlabs.co.in/article/open-erp-magento-integration-new)

**Comment by jagdishpanchal** [comment]
Still Having problem 

I am not able to change the extension but i have Download module (Openlabs_OpenERPConnector-1.4.1.tgz) and tyr to 
Upload package file:   i give path of the module 
it give me error   "Connection string is empty  " in Manage Existing Extensions

**Comment by shalabhaggarwal** [comment]
Hi Jagdish,

These are the steps you should follow:

In magento admin panel go to:
1. System >> Magento Connect >> Magento Connect Manager
2. Key in your username and password.
3. Click on the second tab for settings and change preferred state to 'Beta'. (As of this date the plug-in is beta).
4. Save your settings and select page 1 (Extensions) and paste the following extension key in the box

`http://connect20.magentocommerce.com/community/Openlabs_OpenERPConnector`
1. Continue to install then.

P.S. There is no need for manual installation/upload of package.

**Comment by jagdishpanchal** [comment]
Its done Configure successfully with magento

Thanks For the Help

**Comment by jagdishpanchal** [comment]
Import order is working fine but when i try to  export Order from Openerp to Magento  it do nothing.
I have to do any setting for that ???

**Comment by shalabhaggarwal** [comment]
The export of order status is currently available only for cancelled orders.

Ref: http://openlabs.github.io/magento-integration/sale.html#how-it-works

**Comment by jagdishpanchal** [comment]
Yes got it, it update only status of order in magento.
Suppose i have create one sales order in Openerp and i want send this order data in magento so what i have to do.

**Comment by shalabhaggarwal** [comment]
Exporting orders from OpenERP and creating them in magento is not the correct practice to do and should not be done.

We should only import orders from magento to openerp and the same is implemented.

**Comment by jagdishpanchal** [comment]
Thanks for help and Information

**Comment by jagdishpanchal** [comment]
How manage partner is working(if i create customer in openerp it is created in magento ??) ???

**Comment by shalabhaggarwal** [comment]
Hi @jagdishpanchal 

Right now customers are imported as partners along with orders only.

So when an order is imported, the customer and addresses related to the same are imported to OpenERP.

If you feel that importing all customers in one go is a good option/feature, please create a new issue for the same and we can track the same on that.

**Comment by shalabhaggarwal** [comment]
Hi @jagdishpanchal 

I will close this issue and any more conversations regarding any other issue can be taken up on a different issue.

Thanks.

**Comment by sunnysaroha** [comment]
while install extension key in magento , getting the error

"Couldn't resolve host 'connect20.magentocommerce.com'"
