### ISSUE TITLE
Unable to Import Website

### ISSUE THREAD

**Issue by damiansoriano** [openlabs/magento_integration#67]
Hey there!

I am trying to make the connection between Magento and OpenERP. I am using Magento 1.7.0.2 and OpenERP 7.0.

I just downloaded the magento-integration and in a fresh environment I installed the module. I configure the "Magento instance" in OpenERP, "Test connection" returns "Test connection with magento successful" but when I click "Import Websites" I got the following exception:

```
2013-07-15 17:16:26,762 4117 ERROR oerp70_magento_01 openerp.netsvc: 
Traceback (most recent call last):
  File "/opt/oerpenv/katrina/test70/default/local/lib/python2.7/site-packages/openerp-7.0-py2.7.egg/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/oerpenv/katrina/test70/default/local/lib/python2.7/site-packages/openerp-7.0-py2.7.egg/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/opt/oerpenv/katrina/test70/default/local/lib/python2.7/site-packages/openerp-7.0-py2.7.egg/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/opt/oerpenv/katrina/test70/default/local/lib/python2.7/site-packages/openerp-7.0-py2.7.egg/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/opt/oerpenv/katrina/test70/default/local/lib/python2.7/site-packages/openerp-7.0-py2.7.egg/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/opt/oerpenv/katrina/test70/default/local/lib/python2.7/site-packages/openerp-7.0-py2.7.egg/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/oerpenv/katrina/test70/default/local/lib/python2.7/site-packages/openerp-7.0-py2.7.egg/openerp/addons/magento-integration/wizard/import_websites.py", line 49, in import_websites
    cursor, user, order_config_api.get_states(), context
  File "/opt/oerpenv/katrina/test70/default/local/lib/python2.7/site-packages/openerp-7.0-py2.7.egg/openerp/addons/magento-integration/api.py", line 75, in get_states
    return self.call('sales_order.get_order_states', [])
  File "/opt/oerpenv/katrina/test70/default/local/lib/python2.7/site-packages/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 3: 'Invalid api path.'>
```

I think that the problem is in the "sales_order.get_order_states" magento web service. In a python console, if I execute the following code:

```
from magento.api import API

url = 'http://localhost/magento'
apiuser = '....'
apipass = '....'

with API(url, apiuser, apipass) as order_config_api:
    order_config_api.call('sales_order.get_order_states', [])
```

I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 3: 'Invalid api path.'>
```

It looks like the service "sales_order.get_order_states" does not exists, and I try to find it out and I was unable to find it in Magento. Should I install something additional in my Magento instance?

Thanks!

Damián Soriano

**Comment by shalabhaggarwal** [comment]
Hi Damián,

Thanks for showing interest in our work.

As you would have already understood that the connector implements more features than that provided by the core magento API. This is done by a magento side PHP core API extension developed for this purpose.

Please make sure that you have followed all the configuration steps described on the link below.

https://openerp-magento-connector.readthedocs.org/en/develop/configuration.html

Feel free to revert back in case of any difficulties.

**Comment by damiansoriano** [comment]
Ok, thanks. I was following this tutorial (http://openlabs.github.io/magento-integration/index.html) that now I assume is not the official one and is not updated.

Thanks! Grate job with this module!
