### ISSUE TITLE
Test connection problem

### ISSUE THREAD

**Issue by mikea888** [openlabs/magento_integration#87]
Hi. I have installed everything but upon test connection the following error occurs:

Incorrect API Settings!

Please check and correct the API settings on instance.

I use the Magento admin user in API user and API password.

Have port 8888 after IP address/domain name.  Still won't connect.

**Comment by shalabhaggarwal** [comment]
Hi @mikea888 

Please follow documentation at https://openerp-magento-connector.readthedocs.org/en/develop/

This should guide you through the installation and setup process.

Let me know if you face any difficulties after installation is done.

Thanks!

**Comment by sharoonthomas** [comment]
To be precise the first issue is that the username is not the same as admin username/password. Its a separate web services username and password which is well explained by the documentation link shalabh has sent.

**Comment by mikea888** [comment]
Connection successful now after creating in Magento side webservice user in System>Web Services>SOAP/XML-RPC - Users. But got an error in importing websites as follows:

OpenERP Server Error
Client Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/controllers/main.py", line 1133, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/controllers/main.py", line 1121, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 43, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 31, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 104, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 90, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/netsvc.py", line 293, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 49, in import_websites
    cursor, user, order_config_api.get_states(), context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/magento_integration-develop/api.py", line 75, in get_states
    return self.call('sales_order.get_order_states', [])
  File "/opt/bitnami/python/lib/python2.7/site-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 4: 'Resource path is not callable.'>

**Comment by mikea888** [comment]
con't: Fault 4: 'Resource path is not callable.'

**Comment by shalabhaggarwal** [comment]
Hi @mikea888 

Did you successfully install the magento side extension module as described in Step 1 here - https://openerp-magento-connector.readthedocs.org/en/develop/introduction.html#installation

**Comment by mikea888** [comment]
Yes. Test connection is successful.

**Comment by mikea888** [comment]
I was able to fix above error 'Resource path is not callable' by running compilation process in Magento side under menu System -> Tools -> Compilation. Another error comes up on website importation as follows:

Client Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/controllers/main.py", line 1133, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/controllers/main.py", line 1121, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 43, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 31, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 104, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 90, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/netsvc.py", line 293, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 91, in import_websites
    return self.open_websites(cursor, user, ids, instance, context)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 107, in open_websites
    cursor, user, 'magento_integration', 'instance_website_tree_view'
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/tools/cache.py", line 18, in lookup
    r = self.lookup(self2, cr, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/tools/cache.py", line 46, in lookup
    value = d[key] = self.method(self2, cr, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/base/ir/ir_model.py", line 868, in get_object_reference
    data_id = self._get_id(cr, uid, module, xml_id)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/tools/cache.py", line 18, in lookup
    r = self.lookup(self2, cr, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/tools/cache.py", line 46, in lookup
    value = d[key] = self.method(self2, cr, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/base/ir/ir_model.py", line 861, in _get_id
    raise ValueError('No such external ID currently defined in the system: %s.%s' % (module, xml_id))
ValueError: No such external ID currently defined in the system: magento_integration.instance_website_tree_view
Ok

**Comment by shalabhaggarwal** [comment]
Hi @mikea888 

This issue is coming because the module folder name in your addons folder is `magento_integration-develop`. It should be `magento_integration`

**Comment by mikea888** [comment]
Hi shalab. That did the trick. Thanks.

**Comment by samigosms** [comment]
When I try to make this change to the module directory I get a new error

KeyError: u'magento.instance'

Why is this folder named incorrectly during setup? Shouldn't this be fixed in the documentation? Even if you rename a module directory you will have to restart the entire process because OpenERP is looking for the wrong directory now.

So in short, with the directory named the original way you get this error noted above. Changing the name to just magento_integration causes KeyError: u'magento.instance'
