### ISSUE TITLE
Import Catalog Error

### ISSUE THREAD

**Issue by parthivgls** [openlabs/magento_integration#89]
First of all, great clear work guys :+1: .

started testing the connector, installation went way too smooth.
just installed magento 1.7.0.2, plain instance with no demo data.

Tested connection, successful. 
Import website, successful.
Import Carriers / shipping method, success full.

Now came the real test, import of products from magento store.
Created a product and assigned product to a "Default Category". 
Tried to import it.
and hit with an error.
`Traceback (most recent call last):  
  File "/home/erp/workspace_v7/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/erp/workspace_v7/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/home/erp/workspace_v7/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/home/erp/workspace_v7/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/home/erp/workspace_v7/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/erp/workspace_v7/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/home/erp/workspace_v7/server/openerp/addons/magento_integration/wizard/import_catalog.py", line 36, in import_catalog
    self.import_category_tree(cursor, user, instance, context)
  File "/home/erp/workspace_v7/server/openerp/addons/magento_integration/wizard/import_catalog.py", line 61, in import_category_tree
    category_tree = category_api.tree()
  File "/usr/local/lib/python2.7/dist-packages/magento-0.5dev-py2.7.egg/magento/catalog.py", line 41, in tree
    return self.call('catalog_category.tree', [parent_id, store_view])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.5dev-py2.7.egg/magento/api.py", line 162, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 1: 'Internal Error. Please see log for details.'>`

Now after my little finding I found that an issue with a call made at 
https://github.com/openlabs/magento_integration/blame/develop/wizard/import_catalog.py#L61

Where magento expect either a root category or a store view id / name but hey wait, magento has already that on /app/code/core/Mage/Catalog/Model/Category/Api.php Line number 139. So now what's the cause of an issue !!!

Silly workaround I tried : 
`category_tree = category_api.tree(1)`
and everything seems to be working. 

Cheers,
Parthiv

**Comment by shalabhaggarwal** [comment]
Hi @parthivgls 

Thanks for bringing this to our attention.
A generic solution to this problem would be to have a method on magento-core-api-extension to fetch the root category and use that to fetch the category tree.
So this would prevent any hardcoding to go in.

We will track the progress for this on this issue itself. The magento-core-api-extension patch will be tracked on https://github.com/openlabs/magento-core-api-extension/issues/5
